name: Build & Deploy
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Ruby
        run: sudo apt-get install ruby-full -y
      - name: Install Compass
        run: sudo gem install compass
      - name: Install Global Dependencies
        run: npm install grunt-cli && npm install yarn
      - name: Install Dependencies
        run: yarn
      - name: Run Build
        run: grunt build
      - name: Upload Build
        uses: actions/upload-artifact@v1
        with:
          name: CARA
          path: ./dist